---
# tasks file for zabbix_server

    - name: Install Zabbix Repository Key
      rpm_key: state=present key=http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
    
    - name: install the zabbix
      yum: name=http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm state=present    

    - name: Install zabbix-server
      yum: name={{ item }} state=present
      with_items:
        - zabbix
        - zabbix-server
        - zabbix-server-mysql
        - zabbix-web-mysql

#    - name: Import initial schema
#      mysql_db: name=zabbix state=import target={{item}}
#      with_items:
#        - /usr/share/doc/zabbix-server-mysql-2.2.14/create/schema.sql
#        - /usr/share/doc/zabbix-server-mysql-2.2.14/create/images.sql
#        - /usr/share/doc/zabbix-server-mysql-2.2.14/create/data.sql

    - name: Replace zabbix_server.conf 
      template: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: 'zabbix_server.conf', dest: '/etc/zabbix/zabbix_server.conf' }
        - { src: 'zabbix.conf', dest: '/etc/httpd/conf.d/zabbix.conf' }

    - name: Start zabbix-server, httpd
      service: name={{ item }} state=running
      with_items: 
        - zabbix-server
        - httpd

